[manager]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false
sort_translit = true
show_symlink = true

[preview]
wrap = "yes"
image_filter = "catmull-rom"
image_quality = 90

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, block = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@" &', orphan = true, desc = "Open" },
]

[plugin]
prepend_previewers = [
  { mime = "audio/*",   run = "exifaudio"}
]
